### ISSUE TITLE
uBO dev freezes when typing `:watch-attr` or `:has-text` in My filters

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#2305]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Start typing in My filters `*##style:has-text`, the last `t` will not appear in editor.

Press `t` key again, two `t` will appear.

***

Paste `*##*:matches-css(filter: /blur/):style(filter:none!important;)` into editor, try inserting `:watch-attr` by typing after `*` selector - editor will freeze on `r` this time.

***

Trying to scroll in editor in this frozen state will glitch editor - it will be completely blank.

I think uBO will block all connections in this state - YT video played in background paused because of empty buffer.

***

Chrome console shows:

```
static-filtering-parser.js:1849 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Parser.SelectorCompiler.extractArg (static-filtering-parser.js:1849:18)
    at Parser.SelectorCompiler.compileText (static-filtering-parser.js:1856:18)
    at Parser.SelectorCompiler.compileArgumentAst (static-filtering-parser.js:1801:25)
    at Parser.SelectorCompiler.astCompile (static-filtering-parser.js:1714:35)
    at Parser.SelectorCompiler.compileSelector (static-filtering-parser.js:1463:24)
    at Parser.SelectorCompiler.compile (static-filtering-parser.js:1442:29)
    at Parser.analyzeExtPattern (static-filtering-parser.js:341:35)
    at Parser.analyzeExt (static-filtering-parser.js:236:18)
    at Parser.analyze (static-filtering-parser.js:173:22)
    at Object.token (ubo-static-filtering.js:364:24)
extractArg @ static-filtering-parser.js:1849
compileText @ static-filtering-parser.js:1856
compileArgumentAst @ static-filtering-parser.js:1801
astCompile @ static-filtering-parser.js:1714
compileSelector @ static-filtering-parser.js:1463
compile @ static-filtering-parser.js:1442
analyzeExtPattern @ static-filtering-parser.js:341
analyzeExt @ static-filtering-parser.js:236
analyze @ static-filtering-parser.js:173
token @ ubo-static-filtering.js:364
readToken @ codemirror.js:1168
runMode @ codemirror.js:1225
highlightLine @ codemirror.js:1071
getLineStyles @ codemirror.js:1115
buildLineContent @ codemirror.js:1748
getLineContent @ codemirror.js:2138
updateLineText @ codemirror.js:2146
updateLineForChanges @ codemirror.js:2095
patchDisplay @ codemirror.js:4222
updateDisplayIfNeeded @ codemirror.js:4121
endOperation_W1 @ codemirror.js:3830
endOperations @ codemirror.js:3807
(anonymous) @ codemirror.js:3796
finishOperation @ codemirror.js:2050
endOperation @ codemirror.js:3793
runInOp @ codemirror.js:3922
TextareaInput.poll @ codemirror.js:9535
(anonymous) @ codemirror.js:9320
```

Firefox:

```
15:33:59.107 Uncaught TypeError: can't access property "replace", s is undefined
    extractArg moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1849
    compileText moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1856
    compileArgumentAst moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1801
    astCompile moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1714
    compileSelector moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1463
    compile moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1442
    analyzeExtPattern moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:341
    analyzeExt moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:236
    analyze moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:173
    token moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/codemirror/ubo-static-filtering.js:364
    readToken moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:1168
    runMode moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:1225
    highlightLine moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:1071
    getLineStyles moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:1115
    buildLineContent moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:1748
    getLineContent moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:2138
    updateLineText moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:2146
    updateLineForChanges moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:2095
    patchDisplay moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:4222
    updateDisplayIfNeeded moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:4121
    endOperation_W1 moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:3830
    endOperations moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:3807
    endOperation moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:3796
    finishOperation moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:2050
    endOperation moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:3793
    runInOp moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:3922
    poll moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:9535
    init moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:9320
static-filtering-parser.js:1849:9
15:33:59.506 Uncaught TypeError: can't access property "replace", s is undefined
    extractArg moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1849
    compileText moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1856
    compileArgumentAst moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1801
    astCompile moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1714
    compileSelector moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1463
    compile moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:1442
    analyzeExtPattern moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:341
    analyzeExt moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:236
    analyze moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/static-filtering-parser.js:173
    token moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/js/codemirror/ubo-static-filtering.js:364
    readToken moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:1168
    runMode moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:1225
    highlightLine moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:1071
    highlightWorker moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:3971
    iterN moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:5610
    iterN moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:5712
    iter moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:6098
    highlightWorker moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:3967
    bind moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:148
    onTimeout moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:185
    bind moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/lib/codemirror/lib/codemirror.js:148
static-filtering-parser.js:1849:9

```

### A specific URL where the issue occurs.

http://example.com/

### Steps to Reproduce

above

### Expected behavior

not freezze

### Actual behavior

freeze

### Configuration

Firefox Nightly 107, Chrome 106.0.5249.91, 1.44.5b9.

(This was not filled automatically from Support tab - broken?)

**Comment by gwarser** [comment]
This shows in debugger after clicking on "Revert":

![image](https://user-images.githubusercontent.com/886325/193594705-ceb38db2-a043-41ed-926b-20cc4c42ab07.png)
